# This is a basic workflow to help you get started with Actions

name: Create Workflow Diagrams

# Controls when the workflow will run
on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
    
      - name: PHP Runner
        uses: franzliedke/gh-action-php@0.3.0
      
      
      
      - name: Download File To Workspace
        # You may pin to the exact commit or the version.
        # uses: carlosperate/download-file-action@83d04ab2bc6f9ffa7b6f1ef21c83f630e75d6862
        uses: carlosperate/download-file-action@v2.0.0
        with:
          # URL of the file to download
          file-url: https://raw.githubusercontent.com/WISE-Developers/WISE_Builder_Component/main/.github/workflows/maven-publish.yml
          # New filename to rename the downloaded file
          # file-name: # optional
          # Path to download the file
          # location: # optional, default is .
          # MD5 hash value to check against
          # md5: # optional
          # SHA256 hash value to check against
          # sha256: # optional
      - name: Composer Install
        run: composer install


      - name: Shell
        run: |

          echo Add other actions to build
          ls -lha


      - name: Convert
        run: php8.1 workflows-yaml-to-mermaid.php maven-publish.yml
