# This is a basic workflow to help you get started with Actions

name: Create Workflow Diagrams (JS)
run-name: Create Workflow Diagrams (JS)
# Controls when the workflow will run
# Convert GitHub Actions workflow to Mermaid

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Download Workflow
      uses: carlosperate/download-file-action@v2.0.0
      with:
        file-url: https://raw.githubusercontent.com/WISE-Developers/WISE_Builder_Component/main/.github/workflows/maven-publish.yml


    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nodejs
        npm init -y
        npm install js-yaml
        npm i

    - name: convert
      run: node convert.js


#     - name: Convert workflow
#       run: |
#         echo '```mermaid\ngraph LR\n' > workflow.md
#         cat maven-publish.yml | grep 'name: ' | while read line; do
#           name=$(echo $line | cut -d' ' -f2)
#           echo "  $name[$name]" >> workflow.md
#         done
#         cat maven-publish.yml | grep 'uses: ' | while read line; do
#           name=$(echo $line | cut -d' ' -f2)
#           needs=$(echo $line | cut -d' ' -f3-)
#           for need in $needs; do
#             echo "  $name --> $need" >> workflow.md
#           done
#         done
#         echo '\n```' >> workflow.md

#     - name: show results
#       run: cat workflow.md

#     - name: Commit changes
#       uses: stefanzweifel/git-auto-commit-action@v4
#       with:
#         commit_message: 'Update Mermaid diagram'
#         push: true
#         branch: main
