# This is a basic workflow to help you get started with Actions

name: Create Workflow Diagrams (PHP)
run-name: Create Workflow Diagrams (PHP)
# Controls when the workflow will run
on:
  push:
    branches:
    - main


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Convert"
  Convert:
    name: Convert Workflow to Mermaid
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: Download Workflow
        uses: carlosperate/download-file-action@v2.0.0
        with:
          file-url: https://raw.githubusercontent.com/WISE-Developers/WISE_Builder_Component/main/.github/workflows/maven-publish.yml

      - name: Setup Composer
        run: |
          echo Add other actions to build
          composer init --require=twig/twig:1.13.* -n
          composer require symfony/yaml
          
      - name: Composer Install
        run: composer install

#       - name: Load the PHP Runner
#         uses: franzliedke/gh-action-php@0.3.0
      
      - name: Check PHP Version
        run: php --version
      
      - name: show the workflow
        run: cat maven-publish.yml
      
      - name: Convert Workflow to Mermaid
        run: php workflows-yaml-to-mermaid.php maven-publish.yml
        
#       - name: show the diagram
#         run: cat maven-publish.yml
